name: aplikasi_catatan
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  ulid: ^2.0.1
  flutter_easyloading: ^3.0.5
  form_validator: ^2.1.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
